module.exports = [
	{
		name: "Bachelor Beard Oil",
		price: 1700,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/bachelor-beard-oil.webp",
	},
	{
		name: "Beach Ready Sunglasses",
		price: 2000,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/beach-ready-sunglasses.webp",
	},
	{
		name: "Deluxe Black Set",
		price: 9000,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/black-deluxe-collection.webp",
	},
	{
		name: "Bluetooth Speaker",
		price: 13000,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/bluetooth-speaker.webp",
	},
	{
		name: "Camping Titanium Cup",
		price: 4000,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/camping-titanium-cup.webp",
	},
	{
		name: "Simply Cherry Pie",
		price: 4000,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/cherry-pie.webp",
	},
	{
		name: "Deluxe Chocolate Dessert",
		price: 4500,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/chocolate-deluxe-dessert.webp",
	},
	{
		name: "Citrus Ginger Beer",
		price: 2400,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/citrus-ginger-beer.webp",
	},
	{
		name: "Coffee Coated Mug",
		price: 1700,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/coffee-coated-mug.webp",
	},
	{
		name: "Yellow Submarine",
		price: 3500,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/collectors-edition-sub.webp",
	},
	{
		name: "Intl. Cookie Collection",
		price: 10500,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/cookie-set.webp",
	},
	{
		name: "Classic Gold Watch",
		price: 45000,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/deluxe-gold-watch.webp",
	},
	{
		name: "DIY Design Sneaker",
		price: 37500,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/diy-design-sneaker.webp",
	},
	{
		name: "Camera Lens Flask",
		price: 4000,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/drinking-flask-camera-lens.webp",
	},
	{
		name: "Elite Running Shoes",
		price: 27500,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/elite-running-shoes.webp",
	},
	{
		name: "Ergonomic Mouse",
		price: 9800,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/ergonomic-mouse.webp",
	},
	{
		name: "Exotic Imported Coffee",
		price: 2300,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/exotic-imported-coffee.jpg",
	},
	{
		name: "Fireball Noodle Hotsauce ",
		price: 3500,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/fireball-hotsauce-combo-noodles.webp",
	},
	{
		name: "Fitness Band",
		price: 25000,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/fitness-band.webp",
	},
	{
		name: "Freeze Dried Greens",
		price: 5200,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/freeze-dried-greens.webp",
	},
	{
		name: "Full Body Sunscreen",
		price: 2100,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/fullbody-sunscreen.webp",
	},
	{
		name: "Goblet of Slime",
		price: 3700,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/goblet-of-slime.webp",
	},
	{
		name: "Gold Dusted Pastries",
		price: 8600,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/gold-dusted-pastries.webp",
	},
	{
		name: "Golden Pen",
		price: 11000,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/golden-pen.webp",
	},
	{
		name: "His and Hers Sunglasses",
		price: 11000,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/his-hers-sunglasses.webp",
	},
	{
		name: "Hydrating Facemist",
		price: 2200,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/hydrating-facemist.webp",
	},
	{
		name: "Imported Rejuvenating Tea",
		price: 1800,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/imported-japanese-tea.webp",
	},
	{
		name: "Imported Mineral Water",
		price: 2600,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/imported-mineral-water.webp",
	},
	{
		name: "Imported Seductive Perfume",
		price: 7300,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/imported-perfume.webp",
	},
	{
		name: "Classic Red Lipstick",
		price: 1200,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/imported-red-lipstick.webp",
	},
	{
		name: "Casual Luxury Watch",
		price: 39500,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/luxury-casual-watch.webp",
	},
	{
		name: "Collectors Luxury Watch",
		price: 49500,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/luxury-collectors-watch.webp",
	},
	{
		name: "Makeup Pallette",
		price: 3500,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/makeup-pallette.webp",
	},
	{
		name: "Mini Stool Phone Holder",
		price: 1500,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/mini-stool-phone-holder.webp",
	},
	{
		name: "Minimalist Water Bottle",
		price: 2800,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/minimalist-water-bottle.webp",
	},
	{
		name: "Nesting Doll Set",
		price: 9900,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/nesting-doll-collection.webp",
	},
	{
		name: "Organic Deluxe Red Lipstick",
		price: 1400,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/organic-deluxe-red-lipstick.webp",
	},
	{
		name: "Organic Imported Sunscreen",
		price: 3100,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/organic-imported-sunscreen.webp",
	},
	{
		name: "Organic Pomegranate Bucket",
		price: 7000,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/organic-pomegranate-bucket.webp",
	},
	{
		name: "The Original Tonic Water",
		price: 3200,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/original-tonic-water.webp",
	},
	{
		name: "Outdoor Sunglasses",
		price: 4300,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/outdoor-sunglasses.webp",
	},
	{
		name: "Simply Patches Sneakers",
		price: 15500,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/patches-sneakers.webp",
	},
	{
		name: "Pirate Beard Kit",
		price: 4100,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/pirate-approved-beard-kit.webp",
	},
	{
		name: "Collectors Pirate Coin",
		price: 2400,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/pirate-collecters-coin.webp",
	},
	{
		name: "Royal Absinthe",
		price: 4900,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/royal-absinthe.webp",
	},
	{
		name: "Rugged Outdoor Heels",
		price: 28500,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/rugged-outdoor-heels.webp",
	},
	{
		name: "Speed Demon Helmet",
		price: 50000,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/speed-demon-helmet.webp",
	},
	{
		name: "Spy Camera",
		price: 19900,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/spy-camera.webp",
	},
	{
		name: "Simply Headphones",
		price: 12500,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/studio-headphones.webp",
	},
	{
		name: "Throwback Digital Watch",
		price: 19900,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/throwback-digital-watch.webp",
	},
	{
		name: "Titanium Skewer Holders",
		price: 5900,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/titanium-skewer-holders.webp",
	},
	{
		name: "Triple Deluxe Oatmilk",
		price: 2200,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/triple-deluxe-oatmilk.webp",
	},
	{
		name: "Water Proof Shaker Cup",
		price: 1800,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/water-proof-shaker-cup.webp",
	},
	{
		name: "Wood Carved Knife",
		price: 7900,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/wood-carved-knife.webp",
	},
	{
		name: "Wood Sandals",
		price: 6500,
		currency: "USD",
		image: "https://emporiumproductimages.sfo3.cdn.digitaloceanspaces.com/wood-sandals.webp",
	},
];